version: '3.1'

services:

  db:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_USER: supaUs3r
      POSTGRES_PASSWORD: supaS3cure
      POSTGRES_DB: datababe
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./table_schema.sql:/docker-entrypoint-initdb.d/create_tables.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"