version: '3.1'

services:
  backend:
    image: backend:latest
    build:
      context: backend
    environment:
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_HOST: database
      DB_PORT: 5432
      TABLE_NAME: babe
    ports:
      - '5000:5000'
    link:
      - "db:database"
  db:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./table_schema.sql:/docker-entrypoint-initdb.d/create_tables.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"